### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by breisfeld** [jsnowacki/xppy#1]
Hi,

Your xppy package looks to be a very useful interface to xpp. However, some documentation or examples of usage would help. The README file refers to a 'LaTeX documentation folder', but this is not present in this repository.

Thanks.

**Comment by pkuphy** [comment]
@breisfeld You should install doxygen on your system first, then run `doxygen` command in the project's root directory (there is a `Doxyfile`). After that, you will see the `doc/` directory. Then you `cd doc/latex; make`.
The doc is not well documented. :(

**Comment by jsnowacki** [comment]
Hi, 

Sorry for the delay but apparently I do not have notifications for the xppy repo. Yes, as @pkuphy explained (thanks!) there is some Doxygen-generated documentation but there is not much of it. The documentation is omitted in the repo as it is a standard practice not to include generate docs. I'm not sure if it's explained well but: I can fix that if I have some free time.   

I'm not working currently on the project and, in fact, in the area. So it is really shared as-is, as I do not really have time to work on it. Saying that, if you have some ideas for quick fixes you can either suggest or, even better, sent me pull requests and I'm more than happy to add them

**Comment by caljohnson** [comment]
If anyone else has used this interface successfully, could you share some of that knowledge?  I understand @jsnowacki is quite busy these days.  Any suggestions with how to even get started using the shell, @pkuphy @breisfeld ?  I've figured out how to at least go through a few integrations using xpp and an ode file, but the plot tools are difficult to understand. Also, any ideas on how I would go about running Auto through the shell?  I don't seem to see any reference to it anywhere in the package. @dpvanmaan @aitgon

**Comment by youngmp** [comment]
@drruumms While I can't guarantee any reasonable timeframe, I am slowly adding basic examples for xppy in my fork here https://github.com/youngmp/xppy. Fortunately xppy was extremely well coded, making it possible to reverse engineer virtually all functions.

There is also a better documented python-xpp interface which I have been contributing to here https://github.com/youngmp/Py_XPPCALL

as I understand it, xppy reduces the amount of matplotlib coding and data manipulation, while xppcall allows one to more easily change initial conditions, parameters, and options.

If you have trouble with xppcall please don't hesitate to contact me.

**Comment by jsnowacki** [comment]
Hi, sorry for not commenting. I need to add comment on this package as I'm no longer using xpp and thus modifying this repo. It's for reference only now.
